name:                haskell-stream-playground
version:             0.1.0.0
github:              "githubuser/haskell-stream-playground"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-stream-playground#readme>

dependencies:
- base >= 4.7 && < 5
- conduit >= 1.3.0
- amazonka >= 1.6.1
- amazonka-s3 >= 1.6.1
- amazonka-s3-streaming >= 1.0.0.1
- text >= 1.2.3.0
- lens >= 4.17

library:
  source-dirs: src

executables:
  haskell-stream-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-stream-playground

tests:
  haskell-stream-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-stream-playground
